### ISSUE TITLE
Creating a report containing multiple Tables

### ISSUE THREAD

**Issue by apouliquen** [VahidN/PdfReport.Core#1]
Hello,

I cant find a way to add Page Breaks or even create additional Tables other than by adding the tables once a MainTable or Page event is fired.

Also, it seems the only solution I found to add Plain Text is to create a Table and hide the borders.

Does your library offer a way to do these things in an other way that I haven't seen?

**Comment by VahidN** [comment]
- Use `PdfDoc.NewPage()` in events to add page breaks.
- To create multiple tables with multiple data sources, you will need to create them separately and then merge them as a single PDF file: [sample](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/MergePdfFilesPdfReport.cs)
- Use [events.MainTableAdded](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/TaxPdfReport.cs#L152) to add a new table.
- Use iTextSharp directly to add or create Plain Text only PDF files: [samples](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests)
