### ISSUE TITLE
Could not install on .NetFramework 4.6.2

### ISSUE THREAD

**Issue by mrofia** [VahidN/PdfReport.Core#10]
# Summary of the issue
I got this message when i'm trying to add from nuget
Could not install package 'PdfRpt.Core 1.1.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

## Environment
The in-use version:
Operating system: Windows 10 Pro
IDE: (e.g. Visual Studio 2015)
TargetFramework: 4.6.2

For additional note, i can install EPPlus.Core just fine.
However, for iTextsharp.LGPLv2.Core i got the error below
Unable to resolve dependency 'CoreCompat.System.Drawing'. Source(s) used: 'nuget.org', 'Microsoft and .NET', 'Microsoft Visual Studio Offline Packages'.

**Comment by VahidN** [comment]
- That message means you are using an old version of the NuGet package manager. [Update it first](https://www.nuget.org/downloads) and then set the Package Source to `All` and they will update across different package sources.
- Also you can try [PdfReport](https://github.com/VahidN/PdfReport) for the full .net framework. It's designed just for that environment.

**Comment by VahidN** [comment]
`V 1.1.4` supports .NET 4.x. Give it a try.
