### ISSUE TITLE
Print a bi-dimensional array

### ISSUE THREAD

**Issue by mtugnoli** [VahidN/PdfReport.Core#11]
How is possible print a bi-dimensional array ?

**Comment by VahidN** [comment]
Please post a sample of this array.

**Comment by VahidN** [comment]
You can create a custom data source for it. I added a new sample [BiDimensionalArrayPdfReport](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/BiDimensionalArrayPdfReport.cs#L10) to demonstrate it.
