### ISSUE TITLE
[linux] null exception throw when trying to search for default font

### ISSUE THREAD

**Issue by mahpah** [VahidN/PdfReport.Core#13]
Since `Environment.GetEnvironmentVariable("SystemRoot")` return null, `Path.Combine` will throw exception.

https://github.com/VahidN/PdfReport.Core/blob/9a553bc1125df67d184d4e6daf87a73e82427757/src/PdfRpt.Core/FluentInterface/DataTemplate.cs#L886

dotnet --info

```
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.101/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

```

**Comment by VahidN** [comment]
Fixed via #https://github.com/VahidN/PdfReport.Core/commit/b53047195f9b78881ce92a5a56047d6da396e399

```
 dotnet add package PdfRpt.Core --version 1.1.5 
```
