### ISSUE TITLE
Invoice Report

### ISSUE THREAD

**Issue by mtugnoli** [VahidN/PdfReport.Core#16]
I see all your samples, but seem all make pdf with Tables.

Is it possible to do a Report like a form ? es. Invoice

**Comment by VahidN** [comment]
You can create pdf forms with for instance MS Word or Open Office, etc and then you can fill them using the iTextSharp directly. It's called `acro forms`. You can find 2 samples about AcroForms in src/PdfRpt.Core.FunctionalTests.
