### ISSUE TITLE
Export a Excel file to PDF

### ISSUE THREAD

**Issue by MaximCrabbe** [VahidN/PdfReport.Core#2]
I have been searching all over the internet to be able to convert a xlsx file to PDF (That I created with EPPlus.Core).
However I find no .NET core package that is able to do it. can PdfReport.Core do this?

**Comment by VahidN** [comment]
I added [a new sample](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/ExcelToPdfReport.cs) to show how to read an excel file and then convert it to a PDF Report.
 All you need is a [custom data source which read the excel file](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/ExcelToPdfReport.cs#L52) and then [use this new data source ](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/ExcelToPdfReport.cs#L162). Everything else is the same as before.

**Comment by MaximCrabbe** [comment]
Thanks for the quick reply!
The only problem is with your solution that I need to have predefined columns. Here
 .MainTableColumns(columns =>
                {
                    columns.AddColumn(column =>
                    {
...
                    }
                 }

And for my solution the columns can be dynamic.(it is based on a template and it can change) I understand your solution and thanks but I basicly need to be able to convert just the xlsx to pdf without any further knowledge of the columns. It also just need to take over everything from excel like column width etc without defining it (since it can change etc).
Anyway thanks for adding the sample and fast reply just for that you earned a star.

**Comment by VahidN** [comment]
I changed the `AddColumn` section [to a loop](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/ExcelToPdfReport.cs#L207), using the [ExcelUtils class](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/ExcelToPdfReport.cs#L97).

**Comment by baphamsts** [comment]
Hi, how can we export excel workbook  (Multiple sheets to the one PDF file)?
Either from a completed Excel file or  EPPLus ExcelPackage.

**Comment by VahidN** [comment]
[This sample](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/ExcelToPdfReport.cs) shows you how to read and excel file and then convert it to a PDF report. But ... it reads only one worksheet. You can create multiple PDF reports from different worksheets, with different columns and definitions and then merge them together ([^](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/MergeInMemoryPdfFilesPdfReport.cs), [^](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/MergeMultiplePdfFilesPdfReport.cs), [^](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/MergePdfFilesPdfReport.cs)).

**Comment by baphamsts** [comment]
How quick response! Thank you @VahidN , I will try.
