### ISSUE TITLE
HTML in main table

### ISSUE THREAD

**Issue by godshades** [VahidN/PdfReport.Core#21]
Hi, I want to add HTML table to .MainTable. Can someone give me an example? 
Here is the output I want:  ![img](https://i.imgur.com/ZIZXdP2.png)
I'm trying put the HTML code to PagesHeader.AddPageHeader, but I think it's not a right way and it's output wrong format: ![img](https://i.imgur.com/yFt6Vax.png)

**Comment by VahidN** [comment]
[Try adding borders](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/HtmlHeaderPdfReport.cs#L108):
```csharp
<td style='width:25%;border-bottom-width:0.2; border-bottom-color:red;border-bottom-style:solid'>Department:</td>
```

**Comment by godshades** [comment]
@VahidN  
here is HTML code: https://pastebin.com/DwtU4ncF
here is c#: https://pastebin.com/YusLBE1q

how can I use for loop in AddPageHeader to create HTML like ASP? Can you give me an advice

**Comment by VahidN** [comment]
You have disabled all the columns and data and rows of this report. Don't use PdfReport.Core to just show a header. Use iTextSharp directly for this scenario. Here are some samples about it:
- [HtmlWorkerTests](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/HtmlWorkerTests.cs)
- [Chapter09Tests](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/591270bb05dd512a18de03a528ff24fb07b7a75e/src/iTextSharp.LGPLv2.Core.FunctionalTests/iTextExamples/Chapter09Tests.cs)

**Comment by godshades** [comment]
@VahidN thanks for your example
here is my new code: https://pastebin.com/dBbVqCMp
I'm trying to add style: dotted border but it does not work, Can you help me?

**Comment by VahidN** [comment]
HtmlWorker [doen't support that](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core/iTextSharp/text/html/HtmlTagMap.cs#L127).
