### ISSUE TITLE
Page Break after X rows

### ISSUE THREAD

**Issue by ianvink** [VahidN/PdfReport.Core#27]
# Summary of the issue
This is a wonderful project, bravo and well done!

Is it possible to add a Page Break after set number of rows for a dataSource like this:

```
            .MainTableDataSource(dataSource =>
            {
                dataSource.StronglyTypedList(dataX);
                pageBreakAfterRows(10)
            })
```

**Comment by ianvink** [comment]
or

.PageBreakWhenRowContains("Fred")

**Comment by VahidN** [comment]
You can try setting `NumberOfDataRowsPerPage`. If it sets to zero, NumberOfDataRowsPerPage will be calculated automatically, otherwise as specified. Its default value is 0.
```csharp
.MainTablePreferences(table =>
{
     table.NumberOfDataRowsPerPage(5);
})
```

**Comment by ianvink** [comment]
Thank you Vahid. Your tool is absolutely wonderfully, thank you for your hard work and dedication.
