### ISSUE TITLE
Excel To Pdf in VB.NET

### ISSUE THREAD

**Issue by 010100110111010001100101** [VahidN/PdfReport.Core#28]
Would it be possible to show me in vb.NET how to print an existing Excel file to Pdf please?

I trie to follow the sample posted previously but I cannot for the life of me work it out.

Any help is greatly appreciated.

**Comment by VahidN** [comment]
Try using this online convertor: http://converter.telerik.com/ and feed it with the content of [this file](https://raw.githubusercontent.com/VahidN/PdfReport.Core/master/src/PdfRpt.Core.FunctionalTests/ExcelToPdfReport.cs).

**Comment by 010100110111010001100101** [comment]
Thank you for your help VahidH, I will try and revert back.

**Comment by 010100110111010001100101** [comment]
Thank you for your help VahidN, I will try and revert back.

**Comment by 010100110111010001100101** [comment]
Hi VahidN, ok so I converted it and had a study...

After adding PdfRpt.Core.FunctionalTests.dll to my solution in order to be able to use ExcelToPdfReport I am hit with the following exception:

System.IO.FileLoadException: 'Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

After removal of the dll the app does not break but I am unable to use the ExcelToPdfReport function.

Any ideas?

**Comment by VahidN** [comment]
Try adding its NuGet package to your ptoject first:
```
dotnet add package PdfRpt.Core
```

**Comment by 010100110111010001100101** [comment]
Hi VahidN, this is the error message from your NuGet command:

dotnet : Could not find any project in `C:\TestApp\`.
At line:1 char:1
+ dotnet add package PdfRpt.Core
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Could not find ...TestApp\`.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by VahidN** [comment]
What's your environment's info? What's your Visual studio's version, Which target-framework version is in use?

**Comment by 010100110111010001100101** [comment]
I am using VS 2017 with full .NET framework 4.6.1

**Comment by VahidN** [comment]
You should use the PowerShell command: `Install-Package PdfRpt.Core`

**Comment by 010100110111010001100101** [comment]
Still no luck I'm afriad:

PS C:\Users\******> Install-Package PdfRpt.Core
Install-Package : No match was found for the specified search criteria and package name 'PdfRpt.Core'. Try 
Get-PackageSource to see all available registered package sources.
At line:1 char:1
+ Install-Package PdfRpt.Core
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],  
   Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by VahidN** [comment]
Sorry. I can't help you. You don't know how to install a nuget package. forget about this library.
