### ISSUE TITLE
Convert exisiting excel file to pdf exactly

### ISSUE THREAD

**Issue by manity42** [VahidN/PdfReport.Core#29]
# Summary of the issue
I have been trying out this PDFReport.Core lib.
I have a 3rd party supplied xslm files that i have no control over the format.
It includes pictures, merged columns, formulas and such and empty cells
I can parse the contents of the sheets no problems with EPPlus.
What i cant do is get a exact copy of the sheet with images and formatting to pdf file.
I basically need a result like if i print to PDF printer in windows 10.

I have tried this project as a starting point but it generates exceptions or if the first row does not have information prints a pdf with the message there is no information to display.  I cant add info to the sheets, as they need to be processed without human intervention.
https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/ExcelToPdfReport.cs

How can i create an exact copy of an existing excel sheet as a pdf file, skipping the need for column headers and what not, including images and empty cells.

Any advice appreciated.

## Environment

```
Visual studio 2017
```

## Example code/Steps to reproduce:
https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/ExcelToPdfReport.cs

**Comment by VahidN** [comment]
You can't.
