### ISSUE TITLE
Leading numbers in PagesHeader are moved to the end in reverse order

### ISSUE THREAD

**Issue by boris612** [VahidN/PdfReport.Core#3]
```
.PagesHeader(header =>  {
        header.CacheHeader(cache: true); 
        header.DefaultHeader(defaultHeader =>
        {
          defaultHeader.Message("1 2 3 4 5 abc 6 7 def");
        });
      });
```
Code above produces pages header with the following text 
```abc 6 7 def 5 4 3 2 1```
Leading numbers are moved to the end in reverse order

**Comment by VahidN** [comment]
Yes. If you don't specify the `RunDirection`, the `PdfRunDirection.RightToLeft` will be used. So try adding
```csharp
defaultHeader.RunDirection(PdfRunDirection.LeftToRight);
```

**Comment by boris612** [comment]
```defaultHeader.RunDirection(PdfRunDirection.LeftToRight);```
works and displays:
```1 2 3 4 5 abc 6 7 def```
Thank you. 

Now I'm just curious why
```defaultHeader.RunDirection(PdfRunDirection.RightToLeft);```
displays:
```abc 6 7 def 5 4 3 2 1```
instead of 
```def 7 6 abc 5 4 3 2 1``` 
or 
```fed 7 6 cba 5 4 3 2 1```

**Comment by VahidN** [comment]
Because [FixWeakCharacters](https://github.com/VahidN/PdfReport.Core/blob/2c1ac75e708394a3418a423d822d5dae57b39553/src/PdfRpt.Core/Core/Helper/PersianDate.cs#L27) is in use for RTL.

**Comment by VahidN** [comment]
If you create an HTML DIV with this content:
```xml
<div dir="rtl">
 1 2 3 4 5 abc 6 7 def
</div>
```
You will see the same output in the browser. Because punctuation or numbers, don't have "strong" direction like latin letters or Arabic/Hebrew letters. They are called [weak characters](https://en.wikipedia.org/wiki/Bi-directional_text#weak_characters).

**Comment by boris612** [comment]
OK. I unsterstand now. Thanks for help and explanation. BTW, great tool.
