### ISSUE TITLE
Hige Concurrency

### ISSUE THREAD

**Issue by diegoszch** [VahidN/PdfReport.Core#31]
I would like to know if the library has any limitations regarding the high competition in the generation of pdf files?

**Comment by VahidN** [comment]
- No data will be shared across different threads, so ...
- The only difficulty that I've seen is the collision of produced file names! Use in-memory mode to eliminate the disk IO and the need of creating physical files.

**Comment by diegoszch** [comment]
This is the process I am running.

I have a queue (RabbitMQ) where is stored the data that will be generated the pdfs files. I have a console application that reads the queue data and physically writes the files.

The console application uses several consumers (HostedService) that listen to the messages. If I use only one consumer, the process runs correctly however if I use more than one internal error occurs in lib.

Do you have any idea what might be going on?

Thanks.

This is the exception detail:
Message: Object reference not set to an instance of an object.
Source: iTextSharp.LGPLv2.Core
StackTrace: `"   at iTextSharp.text.FontFactoryImp.GetFont(String fontname, String encoding, Boolean embedded, Single size, Int32 style, BaseColor color, Boolean cached)\n   at iTextSharp.text.FontFactoryImp.GetFont(String fontname, String encoding, Boolean embedded, Single size, Int32 style, BaseColor color)\n   at PdfRpt.Core.Helper.HtmlToPdf.UnicodeFontProvider.GetFont(String fontname, String encoding, Boolean embedded, Single size, Int32 style, BaseColor color, Boolean cached) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/lib/PdfRpt.Core/Core/Helper/HtmlToPdf/UnicodeFontProvider.cs:line 28\n   at iTextSharp.text.FontFactoryImp.GetFont(String fontname, String encoding, Boolean embedded, Single size, Int32 style, BaseColor color)\n   at iTextSharp.text.html.simpleparser.FactoryProperties.GetFont(ChainedProperties props)\n   at iTextSharp.text.html.simpleparser.FactoryProperties.CreateChunk(String text, ChainedProperties props)\n   at iTextSharp.text.html.simpleparser.HtmlWorker.Text(String str)\n   at iTextSharp.text.xml.simpleparser.SimpleXmlParser.flush()\n   at iTextSharp.text.xml.simpleparser.SimpleXmlParser.go(TextReader reader)\n   at iTextSharp.text.html.simpleparser.HtmlWorker.ParseToList(TextReader reader, StyleSheet style, Hashtable interfaceProps)\n   at PdfRpt.Core.Helper.HtmlToPdf.HtmlWorkerHelper.RenderHtml() in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/lib/PdfRpt.Core/Core/Helper/HtmlToPdf/HtmlWorkerHelper.cs:line 74\n   at PdfRpt.HeaderTemplates.HtmlHeaderProvider.createTable(String html, HeaderBasicProperties basicProperties) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/lib/PdfRpt.Core/HeaderTemplates/HtmlHeaderProvider.cs:line 75\n   at PdfRpt.HeaderTemplates.HtmlHeaderProvider.RenderingReportHeader(Document pdfDoc, PdfWriter pdfWriter, IList`1 summaryData) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/lib/PdfRpt.Core/HeaderTemplates/HtmlHeaderProvider.cs:line 65\n   at PdfRpt.Core.Helper.HeaderFooterManager.AddHeader(PdfWriter writer, Document document) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/lib/PdfRpt.Core/Core/Helper/HeaderFooterManager.cs:line 63\n   at PdfRpt.Core.PdfTable.PageEvents.OnStartPage(PdfWriter writer, Document document) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/lib/PdfRpt.Core/Core/PdfTable/PageEvents.cs:line 114\n   at iTextSharp.text.pdf.PdfDocument.InitPage()\n   at iTextSharp.text.Document.Open()\n   at PdfRpt.PdfReportDocument.createPdf() in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/lib/PdfRpt.Core/PdfReportDocument.cs:line 154\n   at PdfRpt.PdfReportDocument.GeneratePdf() in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/lib/PdfRpt.Core/PdfReportDocument.cs:line 84\n   at PdfRpt.FluentInterface.PdfReport.GenerateAsByteArray() in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/lib/PdfRpt.Core/FluentInterface/PdfReport.cs:line 103\n   at Syntesis.SynGW.Works.Reporting.Internals.Layouts.LayoutReportPdf.Generate() in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Works/Syntesis.SynGW.Works.Reporting/Internals/Layouts/LayoutReportPdf.cs:line 239\n   at Syntesis.SynGW.Works.Reporting.Internals.Reports.ReportBase.Generate() in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Works/Syntesis.SynGW.Works.Reporting/Internals/Reports/ReportBase.cs:line 52\n   at Syntesis.SynGW.Works.Reporting.LoadReport.Generate(ReportDocument document, String identifier, IServiceProvider serviceProvider) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Works/Syntesis.SynGW.Works.Reporting/LoadReport.cs:line 40\n   at Syntesis.SynGW.Works.Reporting.ReportEntry.Generate(ReportDocument report, String identifier) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Works/Syntesis.SynGW.Works.Reporting/ReportEntry.cs:line 51\n   at Syntesis.SynGW.Works.Reporting.ReportEntry.ProcessQueue(Byte[] eventBody) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Works/Syntesis.SynGW.Works.Reporting/ReportEntry.cs:line 155\n   at Syntesis.SynGW.Queues.Consumers.Works.Reporting.ConsumerReportingQueue.MessageReceiver(ScopeIoC scope, BasicDeliverEventArgs event) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Queues/Syntesis.SynGW.Queues.Consumers/Works/Reporting/ConsumerReportingQueue.cs:line 38"
`

**Comment by VahidN** [comment]
Try V1.2.8. It has some concurrency checks.

**Comment by diegoszch** [comment]
worked well.

thanks very much.

**Comment by diegoszch** [comment]
I update my version to 1.2.8, but I did more tests and presented another error.

Error: "Collection was modified; enumeration operation may not execute."
My StackTrace
"   at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()\n   at iTextSharp.text.FontFactoryImp.GetFont(String fontname, String encoding, Boolean embedded, Single size, Int32 style, BaseColor color, Boolean cached)\n   at iTextSharp.text.FontFactoryImp.GetFont(String fontname, String encoding, Boolean embedded, Single size, Int32 style, BaseColor color)\n   at PdfRpt.Core.Helper.HtmlToPdf.UnicodeFontProvider.GetFont(String fontname, String encoding, Boolean embedded, Single size, Int32 style, BaseColor color, Boolean cached)\n   at iTextSharp.text.FontFactoryImp.GetFont(String fontname, String encoding, Boolean embedded, Single size, Int32 style, BaseColor color)\n   at iTextSharp.text.html.simpleparser.FactoryProperties.GetFont(ChainedProperties props)\n   at iTextSharp.text.html.simpleparser.FactoryProperties.CreateChunk(String text, ChainedProperties props)\n   at iTextSharp.text.html.simpleparser.HtmlWorker.Text(String str)\n   at iTextSharp.text.xml.simpleparser.SimpleXmlParser.flush()\n   at iTextSharp.text.xml.simpleparser.SimpleXmlParser.go(TextReader reader)\n   at iTextSharp.text.html.simpleparser.HtmlWorker.ParseToList(TextReader reader, StyleSheet style, Hashtable interfaceProps)\n   at PdfRpt.Core.Helper.HtmlToPdf.HtmlWorkerHelper.RenderHtml()\n   at PdfRpt.HeaderTemplates.HtmlHeaderProvider.createTable(String html, HeaderBasicProperties basicProperties)\n   at PdfRpt.Core.Helper.HeaderFooterManager.AddHeader(PdfWriter writer, Document document)\n   at PdfRpt.Core.PdfTable.PageEvents.OnStartPage(PdfWriter writer, Document document)\n   at iTextSharp.text.pdf.PdfDocument.InitPage()\n   at iTextSharp.text.Document.Open()\n   at PdfRpt.PdfReportDocument.createPdf()\n   at PdfRpt.PdfReportDocument.GeneratePdf()\n   at Syntesis.SynGW.Works.Reporting.Internals.Layouts.LayoutReportPdf.Generate() in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Works/Syntesis.SynGW.Works.Reporting/Internals/Layouts/LayoutReportPdf.cs:line 232\n   at Syntesis.SynGW.Works.Reporting.Internals.Reports.ReportBase.Generate() in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Works/Syntesis.SynGW.Works.Reporting/Internals/Reports/ReportBase.cs:line 52\n   at Syntesis.SynGW.Works.Reporting.LoadReport.Generate(ReportDocument document, String identifier, IServiceProvider serviceProvider) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Works/Syntesis.SynGW.Works.Reporting/LoadReport.cs:line 40\n   at Syntesis.SynGW.Works.Reporting.ReportEntry.Generate(ReportDocument report, String identifier) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Works/Syntesis.SynGW.Works.Reporting/ReportEntry.cs:line 51\n   at Syntesis.SynGW.Works.Reporting.ReportEntry.ProcessQueue(Byte[] eventBody) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Works/Syntesis.SynGW.Works.Reporting/ReportEntry.cs:line 155\n   at Syntesis.SynGW.Queues.Consumers.Works.Reporting.ConsumerReportingQueue.MessageReceiver(ScopeIoC scope, BasicDeliverEventArgs event) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Queues/Syntesis.SynGW.Queues.Consumers/Works/Reporting/ConsumerReportingQueue.cs:line 38"`
`

**Comment by diegoszch** [comment]
I imported your project and another error was displayed:

Message: "Object reference not set to an instance of an object."
Source : ` "iTextSharp.LGPLv2.Core"
StackTrace: "   at System.util.collections.OrderedTree.restoreAfterDelete(OrderedTreeNode x)\n   at System.util.collections.OrderedTree.delete(OrderedTreeNode z)\n   at System.util.collections.OrderedTree.Remove(IComparable key)\n   at iTextSharp.text.pdf.PdfWriter.PdfBody.Add(PdfObject objecta, Int32 refNumber, Boolean inObjStm)\n   at iTextSharp.text.pdf.PdfPages.WritePageTree()\n   at iTextSharp.text.pdf.PdfWriter.Close()\n   at iTextSharp.text.Document.Close()\n   at PdfRpt.PdfReportDocument.flushFileInBrowser() in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/lib/PdfRpt.Core/PdfReportDocument.cs:line 178\n   at PdfRpt.PdfReportDocument.createPdf() in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/lib/PdfRpt.Core/PdfReportDocument.cs:line 168\n   at PdfRpt.PdfReportDocument.GeneratePdf() in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/lib/PdfRpt.Core/PdfReportDocument.cs:line 84\n   at PdfRpt.FluentInterface.PdfReport.GenerateAsByteArray() in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/lib/PdfRpt.Core/FluentInterface/PdfReport.cs:line 103\n   at Syntesis.SynGW.Works.Reporting.Internals.Layouts.LayoutReportPdf.Generate() in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Works/Syntesis.SynGW.Works.Reporting/Internals/Layouts/LayoutReportPdf.cs:line 232\n   at Syntesis.SynGW.Works.Reporting.Internals.Reports.ReportBase.Generate() in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Works/Syntesis.SynGW.Works.Reporting/Internals/Reports/ReportBase.cs:line 52\n   at Syntesis.SynGW.Works.Reporting.LoadReport.Generate(ReportDocument document, String identifier, IServiceProvider serviceProvider) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Works/Syntesis.SynGW.Works.Reporting/LoadReport.cs:line 40\n   at Syntesis.SynGW.Works.Reporting.ReportEntry.Generate(ReportDocument report, String identifier) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Works/Syntesis.SynGW.Works.Reporting/ReportEntry.cs:line 51\n   at Syntesis.SynGW.Works.Reporting.ReportEntry.ProcessQueue(Byte[] eventBody) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Works/Syntesis.SynGW.Works.Reporting/ReportEntry.cs:line 155\n   at Syntesis.SynGW.Queues.Consumers.Works.Reporting.ConsumerReportingQueue.MessageReceiver(ScopeIoC scope, BasicDeliverEventArgs event) in /home/syntesis/projects/csharp/Microservices/Syntesis.SynGW/src/Syntesis.SynGW.Queues/Syntesis.SynGW.Queues.Consumers/Works/Reporting/ConsumerReportingQueue.cs:line 38 `

**Comment by VahidN** [comment]
Your scenario needs to put thousands of locks inside the iTextSharp and also this library and I'm not going to do that. Please try this method:
```csharp
// only 1 thread can access the code
private static readonly SemaphoreSlim _semaphoreSlim = new SemaphoreSlim(1,1);

public async Task RunAsync()
{
   await _semaphoreSlim.WaitAsync();
   try
   {
       // Your code here
   }
   finally
   {
      _semaphoreSlim.Release();
   }
}
```
