### ISSUE TITLE
can print pdf file?

### ISSUE THREAD

**Issue by cqwydz** [VahidN/PdfReport.Core#33]
# Summary of the issue

## Environment

```
PdfReport.Core version:
.NET Core SDK version: 
IDE: 
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
[Follow this sample](https://github.com/VahidN/PdfReport/tree/master/Samples/PdfFilePrinter)
