### ISSUE TITLE
Does not support display attribute for using in Enum

### ISSUE THREAD

**Issue by maroufi** [VahidN/PdfReport.Core#35]
# Summary of the issue
I have a data model with enum property. I add display attribute for every element of enum column. I want to see column data with specific name but it does not show this column data with name parameter of display attribute.

## related section:
I am guessing that issue is about [GetColumnPropertyNameAttribute](https://github.com/VahidN/PdfReport.Core/blob/a9adac9e3373d69067fa113c943efda3b7d7aced/src/PdfRpt.Core/Core/Helper/PropertyDataAnnotations.cs) in your source code. You do not support display attribute.

**Comment by VahidN** [comment]
Use `Description` or `DisplayName` attributes instead, such as [this example](https://github.com/VahidN/PdfReport.Core/blob/a9adac9e3373d69067fa113c943efda3b7d7aced/src/PdfRpt.Core.FunctionalTests/Models/CustomerType.cs#L7).

**Comment by maroufi** [comment]
It is problem that `DisplayNameAttribute` is not valid on enumeration.
I use `DisplayAttribute` as a valid attribute.

**Comment by VahidN** [comment]
Post a sample.
