### ISSUE TITLE
Problem in using enum flags in data source

### ISSUE THREAD

**Issue by maroufi** [VahidN/PdfReport.Core#36]
# Summary of the issue
I am using PdfReport.Core in a project. I have problem with enum flags columns. I have data with enum flags type. I expected to see all enumeration comma separated with element display attribute.

## Output:
I could not display data value of every enumeration with friendly names.

**Comment by VahidN** [comment]
Post your enum here.

**Comment by maroufi** [comment]
It is model
`    public class PersonnelReadModel
    {
        [DisplayName("نام پرسنل")]
        public string DisplayName { get; set; }
        [DisplayName("موبایل")]
        public string MobileNumber { get; set; }
        [DisplayName("نقش")]
        public PersonnelRoles? Roles { get; set; }
    }`

and it is related enum flags.
`    [Flags]
    public enum PersonnelRoles
    {
        [Display(Name = "نگهبان")] Guard = 1 << 0,
        [Display(Name = "راننده")] Driver = 1 << 1,
        [Display(Name = "سایر")] Employee = 1 << 3
                                 .
                                 .
                                 .
    }`

**Comment by VahidN** [comment]
Have you tried the [Description attribute](https://github.com/VahidN/PdfReport.Core/blob/a9adac9e3373d69067fa113c943efda3b7d7aced/src/PdfRpt.Core.FunctionalTests/Models/CustomerType.cs#L7)?

**Comment by maroufi** [comment]
yes, I tried with `DescriptionAttribute` but does not work correctly. Its value was like this.
`Guard, Driver, Employee`

**Comment by VahidN** [comment]
Added it via #https://github.com/VahidN/PdfReport.Core/commit/94b4c5b4aeed7ef3fd5b85aa37ee7a4e2127d646
