### ISSUE TITLE
Very big footer

### ISSUE THREAD

**Issue by AliHaydari** [VahidN/PdfReport.Core#38]
Hi
I want create report with :
html header
data list
html footer

but my footer has a very big height, almost half of page and should appear after data list not end of page
how to create this footer?
what about header too?

**Comment by VahidN** [comment]
Add your footer using the [events.MainTableAdded](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/EventsPdfReport.cs#L216).

**Comment by AliHaydari** [comment]
MainTableAdded event  appear only last page
i want on all pages

**Comment by VahidN** [comment]
You can limit the number of rows per page using the [NumberOfDataRowsPerPage](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/IListPdfReport.cs#L66) method. Then add your footer [this way](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/InlineProvidersPdfReport.cs#L51).

**Comment by AliHaydari** [comment]
this not enough good
![01](https://user-images.githubusercontent.com/26842353/68610484-17a94f00-04cd-11ea-809b-c2008d43b7f1.png)

i changing SpacingBeforeTable to -130
![02](https://user-images.githubusercontent.com/26842353/68610650-7ec70380-04cd-11ea-9b0b-84bee65378c7.png)

but its not dynamic
how to make such things dynamically?

**Comment by AliHaydari** [comment]
I suggest add event like MainTableAdded for each pages not only last page
