### ISSUE TITLE
IOException: The document has no pages.

### ISSUE THREAD

**Issue by ruimelo-newtour** [VahidN/PdfReport.Core#4]
When i execute any sample in project get the following error.

What i am doing wrong?

IOException: The document has no pages.
iTextSharp.text.pdf.PdfPages.WritePageTree()

**Comment by VahidN** [comment]
I can't reproduce it
![tst](https://cloud.githubusercontent.com/assets/766010/26005965/0496200c-3750-11e7-91e0-ec445b93c5b3.png)

**Comment by ruimelo-newtour** [comment]
I just call CreateIListPdfReport() this way.
![vs2017](https://cloud.githubusercontent.com/assets/8831259/26008191/a745acce-373b-11e7-8a8e-d5386cdcbf05.PNG)

And here follow the whole stack.

![error](https://cloud.githubusercontent.com/assets/8831259/26008330/35d44da6-373c-11e7-9656-be3ec3ab8129.PNG)

Many thanks

**Comment by VahidN** [comment]
You should change the [Generate method](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/IListPdfReport.cs#L169) here to point to a new new location in your web app:
```csharp
.Generate(data => data.AsPdfFile(TestUtils.GetOutputFileName()));
```
Or If it's a web app, just call [GenerateAsByteArray](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/InMemoryPdfReport.cs#L155)
```csharp
.GenerateAsByteArray(); // creating an in-memory PDF file
```
The result of this method can be used this way:
```csharp
return File(reportBytes, "application/pdf", "name.pdf");
```

**Comment by VahidN** [comment]
I added [a sample web app](https://github.com/VahidN/PdfReport.Core/tree/master/PdfRpt.Core.SampleWebApp) to show how to use this library in an ASP.NET Core web app.

**Comment by ruimelo-newtour** [comment]
Solved, my problem was that i had not the image directory in my application.
My problem was i expecting that in this type of errors, the stack shows a message that indicates the image file was missing. 
But not the message was "The document has no pages.", maybe you can improve this message error in cases like this?

You can close the issue.
Thanks
