### ISSUE TITLE
Remove the dependency on SqlClient

### ISSUE THREAD

**Issue by thiagolunardi** [VahidN/PdfReport.Core#41]
When dealing with PDF, there is no reason to have such coupled dependency. It's okay to have it as extension or ad-don, but not at the Core module.

**Comment by VahidN** [comment]
Well, I'm using it in one of my projects! It's simple and it works :)

**Comment by thiagolunardi** [comment]
Oh, I thought you want to have your component be generic and to be more widely used by the community.

Otherwise, just moving this dependency to another package would be not just nice but also convinient. 

Nevertheless it would be a best practice as well.

**Comment by VahidN** [comment]
It's a common practice in reporting libraries to have more built-in data source providers to make them more convenient and widely used.
