### ISSUE TITLE
Problem with using colspan in HtmlHeaderPdfReport

### ISSUE THREAD

**Issue by raminmjj** [VahidN/PdfReport.Core#42]
Hi
when I add "colspan" in to "td" tag, application throw (Object reference not set to an instance of an object) the exception.

HTML code sample:

`<table style='width: 100%;font-size:9pt;font-family:tahoma;'>
		                        <tr>
			                    <td align='center' bgcolor='#00FF00' colspan='2'>Hello</td>
		                        </tr>
                                        <tr>
                                            <td align = 'right'> Month </td>
                                            <td align = 'right'> Savings </td>
                                        </tr>
                                        <tr>
                                            <td align = 'right'> January </td>
                                            <td align = 'right'>$100 </td>
                                        </tr>
                                      </table>`

I use [this sample](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/HtmlHeaderPdfReport.cs).

**Comment by VahidN** [comment]
I can't reproduce your problem. [I added a colnspan sample here and it works](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/HtmlHeaderPdfReport.cs#L62).
![image](https://user-images.githubusercontent.com/766010/74654523-b5cd4500-519f-11ea-9cbb-c2eb3d607cbb.png)

 Your exception probably comes from somewhere else.

**Comment by raminmjj** [comment]
thank you.
please check it on [HtmlHeaderRtlPdfReport](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/HtmlHeaderRtlPdfReport.cs).
*excuse me, that's my fault. I sent wrong link on first comment.
![image](https://user-images.githubusercontent.com/991847/74657645-ed3ef000-51a5-11ea-84a1-3a3788659ad3.png)

**Comment by VahidN** [comment]
- Update to the latest version.
- Also you should set
```C#
doc.DocumentMargins(new DocumentMargins { Bottom = 100, Left = 36, Right = 36, Top = 36 });
```
