### ISSUE TITLE
alignment for tables cell in HtmlHeaderRtlPdfReport doesn't work

### ISSUE THREAD

**Issue by raminmjj** [VahidN/PdfReport.Core#43]
Hi.
in "[RTL sample](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/HtmlHeaderRtlPdfReport.cs)", alignment doesn't work.

sample code:
`<td width='50%' align='right'>{0}</td>`
`<td width='50%' align='left'>{1}</td>`
everything set to left side.
thank you.

**Comment by molaie** [comment]
Hi.
when document is set ` doc.RunDirection(PdfRunDirection.RightToLeft);` any direction style is computed inverse.
git diff is attached. any solution for this?
i find `createTable()` function in `HtmlHeaderProvider.cs` and added `HorizontalAlignment = HorizontalAlignment.Right` to `PageHeaderProperties` as in diff, but nothing changed.

![Screenshot 2021-06-19 154730](https://user-images.githubusercontent.com/505055/122640598-ace2df80-d115-11eb-8585-57d558512923.png)
