### ISSUE TITLE
‘Microsoft.Jet.OLEDB.4.0' provider is not registered on the local machine

### ISSUE THREAD

**Issue by thibnes** [VahidN/PdfReport.Core#45]
# Summary of the issue

Hello,
when trying to generate a PDF from an excel spreadsheet I got the following exception:
‘Microsoft.Jet.OLEDB.4.0' provider is not registered on the local machine.

Does PdfReport require an external dependency other than iTextSharp and EPPlus?

## Environment

```
PdfReport.Core version: 2.9.4
.NET Framework: 4.6.2 
IDE: VS 2017
```

## Example code/Steps to reproduce:

https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/ExcelToPdfReport.cs

## Output:

```
Exception message: ‘Microsoft.Jet.OLEDB.4.0' provider is not registered on the local machine.
```

**Comment by VahidN** [comment]
Excel files have two formats: new (.xml based/OpenXML based) and the old format (binary). `EPPlus` is designed to read the newer versions of the excel files. 

If this is the structure of your file (open it with [7-zip](http://www.7-zip.org/download.html))
![](https://user-images.githubusercontent.com/766010/30794124-46722ad2-a1d3-11e7-95fa-cc927f23907c.png)
You can't open it with the `EPPlus`. 
This is the structure of the new .xlsx format:
![](https://user-images.githubusercontent.com/766010/30794142-61e9982c-a1d3-11e7-80ef-d6eb33e2cbc5.png)

**Comment by VahidN** [comment]
Also don't use the old [ExcelDataReaderDataSource](https://github.com/VahidN/PdfReport/blob/9799e278d8d8e10eb28fc5cc0757bf0ea793347d/Lib/DataSources/ExcelDataReaderDataSource.cs#L86) here (from the .NET only version of this library). You should use the [this one instead](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/ExcelToPdfReport.cs#L52).
