### ISSUE TITLE
PDF Viewer

### ISSUE THREAD

**Issue by HamedFathi** [VahidN/PdfReport.Core#47]
# Summary of the issue

Does exist any sample to load final PDF output inside a web PDF viewer? Like [Telerik PDF Viewer](https://www.telerik.com/aspnet-core-ui/pdf-viewer) or anything else. 

## Environment

```
PdfReport.Core version: latest
.NET Core SDK version: latest
IDE: VS 2019 latest
```

**Comment by VahidN** [comment]
- For Angular Apps: https://www.dotnettips.info/post/2807
- For React Apps: https://www.dotnettips.info/post/3180/
