### ISSUE TITLE
Question: What is the usage of Export method in PdfReport?

### ISSUE THREAD

**Issue by fenilrathod** [VahidN/PdfReport.Core#48]
There is an Export method in PdfReport type which is accepting ExportToBuilder having methods like ExportToExcel, ExportToCsv and ExportToXml. 

I am not sure what is the usage of it? Is it something we can use to export report to excel or csv using same code as we do for pdf?

**Comment by VahidN** [comment]
This option will create another version of your report (such as an .xlsx file) and then it will embed it in the PDF file as an attachment:

![exports](https://user-images.githubusercontent.com/766010/100116922-86afd680-2e89-11eb-9b5a-407ed4933b76.png)
