### ISSUE TITLE
Invoice Report

### ISSUE THREAD

**Issue by mtugnoli** [VahidN/PdfReport.Core#49]
I see all your samples, all are very interesting, but they are all very vertical grid style.
Is it possible to make a report like this?

![image](https://user-images.githubusercontent.com/459399/100850134-afd0f800-3483-11eb-8644-643925963c59.png)

**Comment by VahidN** [comment]
This is the output of [tax report sample](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/TaxPdfReport.cs):
![tax](https://user-images.githubusercontent.com/766010/100856525-c9cd0380-34a0-11eb-9716-66ea4524fb76.png)

Also you can use the [HtmlHeader](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/HtmlHeaderPdfReport.cs#L75) or [IPageHeader](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/CustomHeaderFooterPdfReport.cs#L203) to customize the header.
