### ISSUE TITLE
Is it possible to merge two in-memory PDFs?

### ISSUE THREAD

**Issue by MildanWorld** [VahidN/PdfReport.Core#5]
So as the title states, I wish to generate 2 PDFs and then merge them and return them as a byte[].

Alternatively, would it be possible to state that on one page you want these columns, and on the next page you want some other columns (from the same data source)?

The point is to make a printable calendar, such that months Jan-Jun are on the first page, and Jul-Dec on the second page.

**Comment by VahidN** [comment]
- Yes. [Here is a sample which shows how to merge multiple in-memory PDF reports](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/MergeInMemoryPdfFilesPdfReport.cs).
- Also I have prepared a [Calendar PdfReport](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/MonthCalendarPdfReport.cs) to show work hours too. It's a custom ColumnItemsTemplate. [Here is a sample](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/CustomCellTemplatePdfReport.cs) which demonstrates how to create a custom cell template. Also [you can use HTML](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/HtmlCellTemplatePdfReport.cs) to customize cells.

**Comment by MildanWorld** [comment]
The first worked, it threw me off that the properties were called FileStreams though, but any stream would do then.. Maybe you should consider renaming them to simply be InputStream and OutputStream?

Second, I'm not sure I could get that to work.. The columns are the months in my case, not the rows that it seems to be in the Calendar PdfReport you linked.
