### ISSUE TITLE
Style seem not run on 

### ISSUE THREAD

**Issue by mtugnoli** [VahidN/PdfReport.Core#50]
In your HtmlHeaderPdfReport sample,
I see 

![image](https://user-images.githubusercontent.com/459399/100873587-b2dbe080-34a3-11eb-81e3-e10eb293b3e6.png)

I expect there are 2 columns with different width, while in all html tables the width is divided proportionally based on the number of columns

![image](https://user-images.githubusercontent.com/459399/100873893-12d28700-34a4-11eb-8970-bbf8c06b02b0.png)

**Comment by VahidN** [comment]
Don't expect too much from the HTML to PDF conversion of iTextSharp. Just create your tables with the related built-in commands such as [this sample](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/CustomHeaderFooterPdfReport.cs#L203).
