### ISSUE TITLE
Last questions :)

### ISSUE THREAD

**Issue by mtugnoli** [VahidN/PdfReport.Core#51]
Sorry for many issues :), I have last 3 questions ...
PS: I like very much your projects and now I'm study this..

1) Is it possible to bold summay cells ?
2) Is it possible to have only bottom border in main table rows ?
3) Is it possible main table fit to available space ?
in my sample 1° page have less space than other because have name,address ivoice text ecc
If I limit rows with NumberOfDataRowsPerPage 1° page will ok, in other it will be a big empty space
if i not limit rows the summary go over footer.

![image](https://user-images.githubusercontent.com/459399/100922987-d5d7b600-34de-11eb-9093-868934ab75a4.png)

![image](https://user-images.githubusercontent.com/459399/100923057-f0aa2a80-34de-11eb-86e1-5748a3f8c653.png)

**Comment by VahidN** [comment]
1- [Yes](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/CustomSummaryPerPagePdfReport.cs#L230).
2- You can define [custom templates](https://github.com/VahidN/PdfReport.Core/tree/master/src/PdfRpt.Core.FunctionalTests/Templates) and then [use them](https://github.com/VahidN/PdfReport.Core/blob/938a95728a2cb66d5af58573c8b912c9b5bd78e3/src/PdfRpt.Core.FunctionalTests/InvoiceRtlPdfReport.cs#L122).
3- change the [SpacingBeforeTable](https://github.com/VahidN/PdfReport.Core/blob/a9adac9e3373d69067fa113c943efda3b7d7aced/src/PdfRpt.Core.FunctionalTests/InlineProvidersPdfReport.cs#L61) value or [Bottom Margin's](https://github.com/VahidN/PdfReport.Core/blob/98a4d0d3205688c255a51a6e8ce2cb27d698c79c/src/PdfRpt.Core.FunctionalTests/HtmlHeaderPdfReport.cs#L30) value.
