### ISSUE TITLE
iTextSharp.LGPLv2.Core v 1.7.1

### ISSUE THREAD

**Issue by merco** [VahidN/PdfReport.Core#52]
# Summary of the issue
iTextSharp.LGPLv2.Core version

## Environment

```
PdfReport.Core version: 1.4.3
.NET Core SDK version:  .Net standard 5
IDE: VS2019
```
We have a project that uses both iTextSharp.LGPLv2.Core v 1.7.1 and PdfReport.Core version: 1.4.3.
It seems that PdfReport.Core is using 1.6.7 version of  iTextSharp.LGPLv2.Core and I get the MissingMethodException.
If I downgrade my project from  iTextSharp.LGPLv2.Core v 1.7.1to 1.6.7 everything runs well.

Is it possibile to fix this ?

Thank you

```
Exception message:
System.MissingMethodException: Method not found PdfReader ctor
Full Stack trace:
```

**Comment by VahidN** [comment]
Update it via #https://github.com/VahidN/PdfReport.Core/commit/60a8563ecc33edc9fe3bdb9230b52f9e31a51b72
