### ISSUE TITLE
Change Direction of Sepecific column

### ISSUE THREAD

**Issue by amin750** [VahidN/PdfReport.Core#53]
How to change direction of specific column in Columns definition?

**Comment by VahidN** [comment]
- You can set the `RunDirection` of [the cell's basic propeties](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/HtmlCellTemplatePdfReport.cs#L177).
- You can create [your own custom cell](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/InlineProvidersPdfReport.cs#L189). [Another example](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/CustomCellTemplatePdfReport.cs#L192).
- [You can use an HTML template for it](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/HtmlCellTemplatePdfReport.cs#L150)
