### ISSUE TITLE
It will be pretty awesome if you include image output of for each PDF sample on your page. That will helps a lot lot.

### ISSUE THREAD

**Issue by yesadahmed** [VahidN/PdfReport.Core#54]
# Summary of the issue

## Environment

```
PdfReport.Core version:
.NET Core SDK version: 
IDE: 
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
[Run this file](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/_1-dotnet-test.bat). After running all of the tests, you can find the final .pdf files in the `bin\out` folder.
