### ISSUE TITLE
AcroForm in page footer and different size of sections

### ISSUE THREAD

**Issue by 1001co** [VahidN/PdfReport.Core#56]
1. is it possible to set AcroForm to page footer as image?
2. is it possible to set width 100% for header and footer  and table width 50% like image below?

 <img src="https://user-images.githubusercontent.com/100206564/163782251-a0c1c7d3-2d9e-44fc-b965-462206d0b308.jpg" width="500">

**Comment by VahidN** [comment]
It's better to use itextsharp directly for your scenario.
