### ISSUE TITLE
Does this mean this does both Excel and PDF exports

### ISSUE THREAD

**Issue by rodsantest1** [VahidN/PdfReport.Core#58]
# Summary of the issue
Does this mean this is all I need to export to Excel and PDF. Currently, my project is using EPPlus for Excel. Will I need to remove that reference?

## Environment
Windows Operating System
```
PdfReport.Core version:
.NET Core SDK version: 
IDE: 
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
This library is limited to EPPlus 4x, because of the changes in its licensing model. So you decide this one for yourself. If you want to use the newer versions of EPPlus, you won't be able to use PdfReport.Core.

**Comment by rodsantest1** [comment]
Thank you. I'm not very good at using sophisticated and modern code, do you know of a reference or tutorial that can help me get up and running with minimal code? For example, let's say I already have the Excel file generated, can I have a console app with very little configuration to produce the PDF?_

**Comment by VahidN** [comment]
[Follow this sample.](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/ExcelToPdfReport.cs)
