### ISSUE TITLE
As Pdf Stream

### ISSUE THREAD

**Issue by jjkom** [VahidN/PdfReport.Core#6]
It is possible to generate a stream instead of a byte array. Can you give us a sample?

**Comment by VahidN** [comment]
Try `AsPdfStream` method to pass your stream (memory-stream/file-stream/...)
```
.Generate(data => data.AsPdfStream(stream));
```

**Comment by jjkom** [comment]
I have tried passing my stream and previous to call Generate the stream is available to read and write, and immediately after the stream appears as disposed.
Is there any workaround to avoid stream dispose?
I want to keep stream alive in order to make file streaming in a Web API.
Thank you for your help.

**Comment by VahidN** [comment]
Sorry I'm not going to change anything.

**Comment by VahidN** [comment]
V1.1 adds the `closeStream` parameter:
```csharp
Generate(data => data.AsPdfStream(stream, closeStream: false))
```

[A sample usage](https://github.com/VahidN/PdfReport.Core/blob/master/PdfRpt.Core.SampleWebApp/Controllers/HomeController.cs#L30)

**Comment by andreyfilipe** [comment]
Hello, again Vahid. I´m trying to configure these fields on Excel. They are int, and the pdf shows they like int, but when i export this pdf to exel, it appears like double, with 1 digit.

![image](https://user-images.githubusercontent.com/12404572/64991080-8be9bc80-d8a7-11e9-84be-7356c74f5de5.png)
![image](https://user-images.githubusercontent.com/12404572/64991142-aae84e80-d8a7-11e9-88c0-0808d930ea89.png)
![image](https://user-images.githubusercontent.com/12404572/64991341-1500f380-d8a8-11e9-9f37-893d694adc2c.png)
Is there any link, to help me??? 
Thank you a lot.
