### ISSUE TITLE
Question: how can we make PdfReport just generate the XLSX?

### ISSUE THREAD

**Issue by ChairmanMawh** [VahidN/PdfReport.Core#61]
Hi Vahid

Suppose we have some requirement like "User A wants the sales report as PDF, User B wants the same sales report as XLSX". I wanted to ask, how can we make PdfReport not bother doing the PDF part, and just give an the XLSX?

I saw the question about using Export to embed an XLSX inside a PDF, but it's not what I mean; I'm looking for some way to have a consistent look for a report, but have the output format be either XLSX or PDF, depending on what I choose..

I figure there may be some way to do that, because PdfRpt is capable of generating an XLSX and attaching it inside the PDF (https://github.com/VahidN/PdfReport.Core/issues/48) so can we make it just give us the generated XLSX and not the PDF .. (Without creating an excel and writing it to file and reading it in to convert again, like https://github.com/VahidN/PdfReport.Core/issues/58 does ?

Thanks

**Comment by VahidN** [comment]
Sorry, No. It's a PDF report with an XLSX addon. It's all or nothing!
