### ISSUE TITLE
Arabic letters does not appear in html header or foort

### ISSUE THREAD

**Issue by khalilme** [VahidN/PdfReport.Core#63]
# Summary of the issue
I used html header and footer, all things are great, but writing Arabic words does not appear, try: مرحبا
when I write English, it shows prefect.
may be its utf code problem.
I tried to use Arabic fonts, I copied them from my Arabic windows, same problem
I tried to use encoded html words such as: #x645;#x634;#x63A;#x644;#x64A; ( I removed & from the beginning)
same problem

**Comment by VahidN** [comment]
[Follow this sample.](https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/HtmlHeaderRtlPdfReport.cs) It's designed for RTL languages.

**Comment by khalilme** [comment]
this is the second time you close an issue directly without respect to us!!
if you have problem with people when they say there is a bug, please write that down in the documents so that we use another library.
ou did it last time, then admit with the problem, why you do that again!

your solution does not work, the previous sample does not work.
I reviewed it, put direction PdfRunDirection.RightToLeft does not fix the problem.
the coloumns are fine, the problem in HTML header.

**Comment by VahidN** [comment]
This is the output of that sample: 
[CreateHtmlHeaderRtlPdfReport.pdf](https://github.com/VahidN/PdfReport.Core/files/11466623/CreateHtmlHeaderRtlPdfReport.pdf)
