### ISSUE TITLE
Unable to find a version of 'EPPlus' that is compatible with 'PdfRpt.Core 1.5.13 constraint: EPPlus (>= 4.5.3.3 && < 5.0.0)'.					

### ISSUE THREAD

**Issue by AlaJaber97** [VahidN/PdfReport.Core#66]
use EPPlus version 7.2.2, and try to install PdtRpt.Core but is not working

I get this error
 "Unable to find a version of 'EPPlus' that is compatible with 'PdfRpt.Core 1.5.13 constraint: EPPlus (>= 4.5.3.3 && < 5.0.0)'."

**Comment by VahidN** [comment]
Yes, because of its licensing issues. I started this project when its license was something else.
