### ISSUE TITLE
HtmlHeaderPdfReport table width is always bisect

### ISSUE THREAD

**Issue by Nokecy** [VahidN/PdfReport.Core#9]
# Summary of the issue
https://github.com/VahidN/PdfReport.Core/blob/master/src/PdfRpt.Core.FunctionalTests/HtmlHeaderPdfReport.cs#L108-L114

## Environment

```
The in-use version:
Operating system: 
IDE: (e.g. Visual Studio 2015)
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
؟؟
